services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432" 


  odoo12:
    image: odoo:12
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "20012:8072" # live chat
    volumes:
      - ./addons:/mnt/extra-addons
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -u hr_applicant_custom --db-filter=^job_applications$ --dev xml
